### PR TITLE
General Bugfixes & Improvements

### PR DESCRIPTION
**Pull request by hansemannn**
(work in progress)

### CODE REVIEW

**Comment by julien9999** [comment]
@hansemannn, this module looks great but currently not working. 
Could you merge and check if example is still working as is?
Thanks

**Comment by julien9999** [comment]
Good morning @hansemannn, when you have a moment please take a look at this awesome module.
Thanks

**Comment by julien9999** [comment]
Good morning @hansemannn, when you have a moment if you could give an update on this module it would be awesome.
Thanks

**Comment by vijaysingh-axway** [comment]
@julien, I’ll work on this next week. Thanks!

**Comment by julien9999** [comment]
Awesome news. 
Thanks.

**Comment by julien9999** [comment]
hi @vijaysingh-axway, are you planning on documenting example-view-camera.js file? thanks

**Comment by hansemannn** [comment]
@julien9999 Please relax. It's being worked on.

**Comment by julien9999** [comment]
Thanks. Sorry, in no way it was intended to rush you.

**Pull request merged**
